source_url: https://data.chc.ucsb.edu/products/CHIRPS-GEFS/v3/daily/global
start_date: 2001-01-03
end_date: 2002-01-01
frequency: D
forecast: True
extra_dims:
  - leadtime : int
test:
  start_date: 2001-01-01
  end_date: 2001-01-02
  iso3s: ["BDI", "NGA", "TCD"]
