blob_prefix: floodscan/daily/v5/processed/aer_area_300s_
start_date: 1998-01-12
end_date: Null
forecast: False
extra_dims:
  - band : str
test:
  start_date: 2023-12-01
  end_date: 2024-01-31
  iso3s: ["ETH"]
