blob_prefix: floodscan/daily/v5/processed/global/aer_area_300s_
start_date: 1998-01-12
end_date: Null
frequency: D
forecast: False
extra_dims:
  - band : str
test:
  start_date: 1998-01-12
  end_date: Null
  iso3s: ["BDI", "NGA", "TCD"]
